all:
  hosts:
    mc.computecanada.dev:
      ansible_user: centos
      fqdn: mc.computecanada.dev
      saml_identity_provider_metadata_url: https://idp.computecanada.ca/idp/shibboleth
      saml_identity_provider_entity_id: https://idp.computecanada.ca/idp/shibboleth
      saml_service_provider_entity_id: mc.computecanada.dev
      server_admin_email: frederic.fortier-chouinard@calculquebec.ca
      magic_castle_ui_version: "v5.1.0"